/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Shehan
 */
public class Form_GuestsRoom extends javax.swing.JFrame {

    /**
     * Creates new form Form_GuestsRoom
     */
    private Connection connection = null;
    private Statement statement = null;
    private ResultSet resultSet = null;
    private final String url = "jdbc:mysql://localhost:3306/hotelsystem";
    private final String user = "root";
    private final String password = "";
    private final String driver = "com.mysql.jdbc.Driver";
    
    private String type;
    public Form_GuestsRoom() {
        initComponents();
        try
        {
            Class.forName(driver);
            connection = DriverManager.getConnection(url,user,password);
            statement=connection.createStatement();
            
            
        } catch (Exception ex)
        {
            Logger.getLogger(Form_CheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        Submit.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        currentRoom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        newRoom = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        RType = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        GuestName = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 50, 86));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Change Guest's Room");

        jButton1.setBackground(new java.awt.Color(100, 255, 218));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Current Room Number:");

        currentRoom.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        currentRoom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                currentRoomActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("New Room Number:");

        newRoom.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        newRoom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newRoomActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Room Type:");

        String url = "jdbc:mysql://localhost:3306/hotelsystem";
        String user = "root";
        String password = "";
        String driver = "com.mysql.jdbc.Driver";
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;

        int num2 = 0;
        try
        {
            connection = DriverManager.getConnection(url,user,password);
            statement=connection.createStatement();

            String sql ="SELECT COUNT(DISTINCT type) AS 'types' FROM room";
            resultSet = statement.executeQuery(sql);
            while(resultSet.next())
            {
                num2=resultSet.getInt("types");
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }

        String type[] = new String[num2];

        try
        {
            connection = DriverManager.getConnection(url,user,password);
            statement=connection.createStatement();

            String sql ="SELECT DISTINCT type FROM room";
            resultSet = statement.executeQuery(sql);
            int i = 0;
            while(resultSet.next())
            {
                type[i]=resultSet.getString("type");
                i = i + 1;
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        RType.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        RType.setModel(new javax.swing.DefaultComboBoxModel<>(type));
        RType.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RTypeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Guest's Name:");

        GuestName.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        GuestName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        GuestName.setEnabled(false);
        GuestName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GuestNameActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(100, 255, 218));
        Submit.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        Submit.setText("Submit");
        Submit.setToolTipText("");
        Submit.setBorder(null);
        Submit.setBorderPainted(false);
        Submit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currentRoom)
                            .addComponent(GuestName)
                            .addComponent(RType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentRoom))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuestName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Form_Reservation1 R = new Form_Reservation1();
        R.setVisible(true);
        R.setTab(1);
        R.setLocationRelativeTo(this);
        R.setExtendedState(this.getExtendedState());
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void currentRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentRoomActionPerformed

        String NumberPattern = "[0-9]+";
         Submit.setEnabled(false);
        
        if(!currentRoom.getText().matches(NumberPattern))
        {
            Form_Alerts A = new Form_Alerts("Please Check the Number");
            A.setDefaultCloseOperation(0);
            A.setVisible(true);
            A.setLocationRelativeTo(this);
            return;
        }
        
        int curRm = Integer.valueOf(currentRoom.getText());
        
        

        String driver = "com.mysql.jdbc.Driver";
        try 
        {
        Class.forName(driver);
        }
        catch (ClassNotFoundException e) 
        {
        e.printStackTrace();
        }
        
        String sql = "SELECT guest.name,room.type FROM guest,room WHERE room.GuestID=guest.id AND room.number="+curRm;
        
        try
           {
            GuestName.setText("");
            resultSet = statement.executeQuery(sql);
            
            while(resultSet.next())
            {
                String name = resultSet.getString("name");
                GuestName.setText(name);
                type = resultSet.getString("type").toString();
                RType.setSelectedItem(type);
                RType.setEnabled(false);
                
                if(name!=null || !name.equals(""))
                {
                    Submit.setEnabled(true);
                }
                else
                {
                    GuestName.setText("");
                    RType.setSelectedItem(null);
                    newRoom.setSelectedItem(null);
                    return;
                }
                
            }
        }
        catch (Exception e) 
            {
            e.printStackTrace();
            }
        
        String type = String.valueOf(RType.getSelectedItem());
        
        String sql2 = "SELECT COUNT(number) FROM room WHERE Booked = 0 AND type='"+type+"'";
        int count = 0;
        try
           {

            resultSet = statement.executeQuery(sql2);
            while(resultSet.next())
            {
                count = resultSet.getInt("COUNT(number)");
            }
        }
        catch (Exception e) 
            {
            e.printStackTrace();
            }
        String rooms[] = new String[count];
        
        
        String sql3 = "SELECT number FROM room WHERE Booked = 0 AND type='"+type+"'";
        try
           {

            resultSet = statement.executeQuery(sql3);
            int i = 0;
            while(resultSet.next())
            {
                rooms[i] = String.valueOf(resultSet.getInt("number"));
                i = i + 1;
            }
        }
        catch (Exception e) 
            {
            e.printStackTrace();
            }
        
        newRoom.setModel(new javax.swing.DefaultComboBoxModel<>(rooms));


    }//GEN-LAST:event_currentRoomActionPerformed

    private void RTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTypeActionPerformed
      String type = String.valueOf(RType.getSelectedItem());
      
        

        try 
        {
        Class.forName(driver);
        }
        catch (ClassNotFoundException e) 
        {
        e.printStackTrace();
        }
        
        
        String sql2 = "SELECT COUNT(number) FROM room WHERE Booked = 0 AND type='"+type+"'";
        int count = 0;
        try
           {

            resultSet = statement.executeQuery(sql2);
            while(resultSet.next())
            {
                count = resultSet.getInt("COUNT(number)");
            }
        }
        catch (Exception e) 
            {
            e.printStackTrace();
            }
        String rooms[] = new String[count];
        
        
        String sql3 = "SELECT number FROM room WHERE Booked = 0 AND type='"+type+"'";
        try
           {

            resultSet = statement.executeQuery(sql3);
            int i = 0;
            while(resultSet.next())
            {
                rooms[i] = String.valueOf(resultSet.getInt("number"));
                i = i + 1;
            }
        }
        catch (Exception e) 
            {
            e.printStackTrace();
            }
        
        newRoom.setModel(new javax.swing.DefaultComboBoxModel<>(rooms));
    }//GEN-LAST:event_RTypeActionPerformed

    private void GuestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuestNameActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        int oldroom = Integer.valueOf(currentRoom.getText());
        int newroom = Integer.valueOf(String.valueOf(newRoom.getSelectedItem()));
        int BID,GID;
        BID=GID=0;
        
        
        
        
        
        String sql = "SELECT BookingID,GuestID FROM room WHERE number="+oldroom;
        
        try{
            resultSet = statement.executeQuery(sql);
            
            while(resultSet.next())
            {
                BID = resultSet.getInt("BookingID");
                GID = resultSet.getInt("GuestID");
            }
           }
        catch (Exception e) {
        e.printStackTrace();
        }
        
        
        String sql2 = "UPDATE room SET BookingID = null,GuestID=null,Booked=0 WHERE number="+oldroom;
        
        String sql3 = "UPDATE room SET BookingID="+BID+", GuestID="+GID+",Booked=1 WHERE number="+newroom;
        
        try 
		{
			
			PreparedStatement pst = connection.prepareStatement(sql2);
			pst.executeUpdate();
                        PreparedStatement pst2 = connection.prepareStatement(sql3);
			pst2.executeUpdate();
		}
		catch(SQLException e)
		{
			System.out.println(e.getMessage());
		}
        
        Form_Alerts A = new Form_Alerts("Guest has been moved to the new room");
        A.setDefaultCloseOperation(0);
        A.setVisible(true);
        A.setLocationRelativeTo(this);
        
        
        
        
        
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void newRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_GuestsRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_GuestsRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_GuestsRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_GuestsRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_GuestsRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GuestName;
    private javax.swing.JComboBox<String> RType;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField currentRoom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> newRoom;
    // End of variables declaration//GEN-END:variables
}
