/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Shehan
 */
public class Form_Halls extends javax.swing.JFrame
{

    /**
     * Creates new form Form_Halls
     */
    
    private Connection connection = null;
    private Statement statement = null;
    private ResultSet resultSet = null;
    private final String url = "jdbc:mysql://localhost:3306/hotelsystem";
    private final String user = "root";
    private final String password = "";
    private final String driver = "com.mysql.jdbc.Driver";
    private String temp[] = new String[4];
    
    public Form_Halls()
    {
        initComponents();
        jTable1.setAutoCreateRowSorter(true);
        DeleteBooking.setEnabled(false);
        try
        {
            Class.forName(driver);
            connection = DriverManager.getConnection(url,user,password);
            statement=connection.createStatement();
            
            
        } catch (Exception ex)
        {
            Logger.getLogger(Form_CheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            
            temp [0] = (String) jTable1.getValueAt(jTable1.getSelectedRow(),0);
            temp [1] = (String) jTable1.getValueAt(jTable1.getSelectedRow(),1);
            temp [2] = (String) jTable1.getValueAt(jTable1.getSelectedRow(),2);
            temp [3] = (String) jTable1.getValueAt(jTable1.getSelectedRow(),3);
            if (temp[0]!=null)
            {
                DeleteBooking.setEnabled(true);
            }
            
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DeleteBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 50, 86));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hall Reservations");

        jButton1.setBackground(new java.awt.Color(100, 255, 218));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        BDate.setBackground(new java.awt.Color(255, 255, 255));
        BDate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BDateActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date:");

        jTable1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Hall", "Guest Name", "Date", "Time"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        DeleteBooking.setBackground(new java.awt.Color(100, 255, 218));
        DeleteBooking.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        DeleteBooking.setText("Delete Reservation");
        DeleteBooking.setToolTipText("");
        DeleteBooking.setBorderPainted(false);
        DeleteBooking.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DeleteBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 161, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(BDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(DeleteBooking)
                        .addContainerGap(143, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        Form_Reservation1 R = new Form_Reservation1();
        R.setVisible(true);
        R.setTab(1);
        R.setLocationRelativeTo(this);
        R.setExtendedState(this.getExtendedState());
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BDateActionPerformed
    {//GEN-HEADEREND:event_BDateActionPerformed
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][]
        {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String []
        {
            "Hall", "Guest Name", "Date", "Time"
        }
    )
    {
        boolean[] canEdit = new boolean []
        {
            false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex)
        {
            return canEdit [columnIndex];
        }
    });
        
        String content[][] = null;
        
        Date d =  BDate.getDate();
        java.sql.Date date = new java.sql.Date(d.getTime());
        try
           {
               String sql =    "SELECT COUNT(*) " 
                                +"FROM guest,reservation " 
                                +"WHERE reservation.guestId = guest.ID " 
                                +"AND reservation.date = '"+date+"'";
                resultSet = statement.executeQuery(sql);
                    while(resultSet.next())
                    {
                        content = new String[resultSet.getInt("COUNT(*)")][4];
                    }
                    
                    
                int i = 0;
                String sql2 =    "SELECT reservation.type,guest.name,reservation.date,reservation.time  " 
                                +"FROM guest,reservation " 
                                +"WHERE reservation.guestId = guest.ID " 
                                +"AND reservation.date = '"+date+"'";
                resultSet = statement.executeQuery(sql2);
                    while(resultSet.next())
                    {
                        content[i][0] = resultSet.getString("type");
                        content[i][1] = resultSet.getString("name");
                        content[i][2] = resultSet.getDate("date").toString();
                        if(resultSet.getInt("time")<12)
                        {
                            content[i][3] = "Lunch";
                        }
                        else
                        {
                            content[i][3] = "Dinner";
                        }
                        i++;
                    }

        
                    
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    content,
                    new String []
                    {
                        "Hall", "Guest Name", "Date", "Time"
                    }
                )
                {
                    boolean[] canEdit = new boolean []
                    {
                        false, false, false, false
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex)
                    {
                        return canEdit [columnIndex];
                    }
                });
        
        }
        catch (Exception e) 
            {
            e.printStackTrace();
            }
        
    }//GEN-LAST:event_BDateActionPerformed

    private void DeleteBookingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DeleteBookingActionPerformed
    {//GEN-HEADEREND:event_DeleteBookingActionPerformed

        int time;
        try{
            if(temp[3].equalsIgnoreCase("Lunch"))
            {
                time = 10;
            }
            else
            {
                time = 18;
            }
        
        int ID = 0;
        String sql ="SELECT date,id "
                        + "FROM reservation "
                        + "WHERE date='"+temp[2]+"' "
                        + "AND time ="+time;
            resultSet = statement.executeQuery(sql);
            
            while(resultSet.next())
            {
                Date date = resultSet.getDate("date");
                Date today = new Date();
                ID = resultSet.getInt("id");
                if(today.after(date) || today.equals(date))
                {
                    Form_Alerts A = new Form_Alerts("This Booking cannot be cancelled, check date");
                    A.setDefaultCloseOperation(0);
                    A.setVisible(true);
                    A.setLocationRelativeTo(this);
                    return;
                }
            }
            
            
        String message;
        String sql3 ="SELECT Sender,Message,Receiver "
                        + "FROM messages "
                        + "WHERE Message LIKE '%Delete Hall Reservation%'";
            resultSet = statement.executeQuery(sql3);
            
            while(resultSet.next())
            {
                if(resultSet.getString("Sender").equalsIgnoreCase("Receptionist") && resultSet.getString("Receiver").equals("Accounting"))
                {
                    message = resultSet.getString("Message");
                    message = message.replaceAll("\\D+","");
                    
                    if(Integer.parseInt(message)==ID)
                    {
                        Form_Alerts A = new Form_Alerts("Deletion of this Reservation has already been requested.");
                        A.setDefaultCloseOperation(0);
                        A.setVisible(true);
                        A.setLocationRelativeTo(this);
                        return;
                    }
                }
            }
           
        
        String sql5 = "INSERT INTO messages(Sender,Message,Receiver) VALUES('Receptionist',"
                        + "'Delete Hall Reservation: Reservation ID = "+ID+"','Accounting')";
                
                        PreparedStatement pst = connection.prepareStatement(sql5);
                        pst.executeUpdate();
            
            
            
            
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
        Form_Alerts A = new Form_Alerts("Accounting will delete the Reservation.");
        A.setDefaultCloseOperation(0);
        A.setVisible(true);
        A.setLocationRelativeTo(this);
        
        
    }//GEN-LAST:event_DeleteBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Form_Halls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Form_Halls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Form_Halls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Form_Halls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Form_Halls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker BDate;
    private javax.swing.JButton DeleteBooking;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
