/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Shehan
 */
public class Form_HallBookings extends javax.swing.JFrame
{

    /**
     * Creates new form Form_HallBookings
     */
    private Connection connection = null;
    private Statement statement = null;
    private Statement statement2 = null;
    private ResultSet resultSet = null;
    private ResultSet resultSet2 = null;
    private final String url = "jdbc:mysql://localhost:3306/hotelsystem";
    private final String user = "root";
    private final String password = "";
    private final String driver = "com.mysql.jdbc.Driver";
    
    
    private Guest G;
    
    public Form_HallBookings()
    {
        initComponents();
        try
        {
            Class.forName(driver);
            connection = DriverManager.getConnection(url,user,password);
            statement=connection.createStatement();
            
            
        } catch (Exception ex)
        {
            Logger.getLogger(Form_CheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        Calendar c = BDate.getMonthView().getCalendar();
        c.setTime(new Date());
        BDate.getMonthView().setLowerBound(c.getTime());
        HType.setEnabled(false);
        HType1.setEnabled(false);
        HSubmit.setEnabled(false);
        HSubmit.setText("Calculate");
        
        String halls[] = null;
        
        try
        {
        String sql2 = "SELECT COUNT(number) FROM halls WHERE type LIKE '%Hall%'";
                resultSet = statement.executeQuery(sql2);
                while(resultSet.next())
                {
                    halls = new String[resultSet.getInt("COUNT(number)")];
                }
                
                
        int i = 0;
        String sql3 = "SELECT type FROM halls WHERE type LIKE '%Hall%' ";
                resultSet = statement.executeQuery(sql3);
                while(resultSet.next())
                {
                    halls[i] = resultSet.getString("type");
                    i++;
                }
        
         
        }catch(Exception e)
        {
            e.printStackTrace();
                    
        }
        
        
        HType1.setModel(new javax.swing.DefaultComboBoxModel<>(halls));
        HType1.setSelectedItem(null);
        HType.setSelectedItem(null);
        
    }
    
    public Form_HallBookings(Guest G)
    {
        initComponents();
        try
        {
            Class.forName(driver);
            connection = DriverManager.getConnection(url,user,password);
            statement=connection.createStatement();
            
            
        } catch (Exception ex)
        {
            Logger.getLogger(Form_CheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        this.G = G;
        Calendar c = BDate.getMonthView().getCalendar();
        c.setTime(new Date());
        BDate.getMonthView().setLowerBound(c.getTime());
        HType.setEnabled(false);
        HType1.setEnabled(false);
        HSubmit.setEnabled(false);
        HSubmit.setText("Calculate");
        
        String halls[] = null;
        
        try
        {
        String sql2 = "SELECT COUNT(number) FROM halls WHERE type LIKE '%Hall%' ";
                resultSet = statement.executeQuery(sql2);
                while(resultSet.next())
                {
                    halls = new String[resultSet.getInt("COUNT(number)")];
                }
                
                
        int i = 0;
        String sql3 = "SELECT type FROM halls WHERE type LIKE '%Hall%' ";
                resultSet = statement.executeQuery(sql3);
                while(resultSet.next())
                {
                    halls[i] = resultSet.getString("type");
                    i++;
                }
        
         
        }catch(Exception e)
        {
            e.printStackTrace();
                    
        }
        
        
        HType1.setModel(new javax.swing.DefaultComboBoxModel<>(halls));
        HType1.setSelectedItem(null);
        HType.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        HType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        HType1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        HSubmit = new javax.swing.JButton();
        HCheck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 50, 86));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hall Bookings");

        jButton1.setBackground(new java.awt.Color(100, 255, 218));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        BDate.setBackground(new java.awt.Color(255, 255, 255));
        BDate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BDate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BDateActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date:");

        HType.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        HType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunch", "Dinner" }));
        HType.setToolTipText("");
        HType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HType.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                HTypeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Type:");

        HType1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        HType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hall 01", "Hall 02" }));
        HType1.setToolTipText("");
        HType1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HType1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                HType1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hall:");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        HSubmit.setBackground(new java.awt.Color(100, 255, 218));
        HSubmit.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        HSubmit.setText("Calculate");
        HSubmit.setToolTipText("");
        HSubmit.setBorder(null);
        HSubmit.setBorderPainted(false);
        HSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                HSubmitActionPerformed(evt);
            }
        });

        HCheck.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        HCheck.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(BDate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(HType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(HType1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        Form_Reservation1 R = new Form_Reservation1();
        R.setVisible(true);
        R.setLocationRelativeTo(this);
        R.setExtendedState(this.getExtendedState());
        R.setText(G.getName(),G.getNumber(),G.getType(),G.getEmail());
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BDateActionPerformed
    {//GEN-HEADEREND:event_BDateActionPerformed
    HSubmit.setText("Calculate");
    HType.setEnabled(true);
    HType1.setEnabled(false);
    jLabel11.setText("");
    }//GEN-LAST:event_BDateActionPerformed

    private void HTypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_HTypeActionPerformed
    {//GEN-HEADEREND:event_HTypeActionPerformed
       
        
        HSubmit.setText("Calculate");
        jLabel11.setText("");
        HType1.setEnabled(true);
    }//GEN-LAST:event_HTypeActionPerformed

    private void HType1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_HType1ActionPerformed
    {//GEN-HEADEREND:event_HType1ActionPerformed
        HCheck.setText("");
       HSubmit.setText("Calculate");
       jLabel11.setText(""); 
       if(BDate.getDate()!=null)
       {
        java.sql.Date date = new java.sql.Date(BDate.getDate().getTime());
        int Number = 0;
        int time = 0;
        if(HType.getSelectedItem().toString().equalsIgnoreCase("Lunch"))
             {
                 time = 10;
             }
             else
             {
                 time = 18;
             }



         try{      
             String sql2 = "SELECT number FROM halls WHERE type='"+HType1.getSelectedItem().toString()+"' ";
                 resultSet = statement.executeQuery(sql2);
                 while(resultSet.next())
                 {
                     Number = resultSet.getInt("number");
                 }


             String sql4 = "SELECT tableNo,time,date FROM reservation WHERE tableNo='"+Number+"' AND time = "+time+" AND date='"+date+"'";
                 resultSet = statement.executeQuery(sql4);
                 while(resultSet.next())
                 {
                     HCheck.setText("Not Available");
                     HSubmit.setText("Calculate");
                     jLabel11.setText("");
                     HSubmit.setEnabled(false);
                     return;
                 }




             }
          catch (Exception e) {
                 e.printStackTrace();
                 }
         HSubmit.setEnabled(true);
       }
    }//GEN-LAST:event_HType1ActionPerformed

    private void HSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_HSubmitActionPerformed
    {//GEN-HEADEREND:event_HSubmitActionPerformed
       java.sql.Date date = new java.sql.Date(BDate.getDate().getTime());
       int Number = 0;
       int time = 0;
       if(HType.getSelectedItem().toString().equalsIgnoreCase("Lunch"))
            {
                time = 10;
            }
            else
            {
                time = 18;
            }
       
       double amount = 0;
       
        try{      
            String sql2 = "SELECT number FROM halls WHERE type='"+HType1.getSelectedItem().toString()+"' ";
                resultSet = statement.executeQuery(sql2);
                while(resultSet.next())
                {
                    Number = resultSet.getInt("number");
                }
                
            
            if(HSubmit.getText().equalsIgnoreCase("Calculate"))
            {
                String sql3 = "SELECT price,number FROM halls WHERE type='"+HType1.getSelectedItem().toString()+"' ";
                resultSet = statement.executeQuery(sql3);
                while(resultSet.next())
                {
                    jLabel11.setText("Advance Due: "+(resultSet.getDouble("Price")*0.25));
                }
                HSubmit.setText("Submit");
                return;
             }
            
            
            
            String sql4 = "SELECT price,number FROM halls WHERE type='"+HType1.getSelectedItem().toString()+"' ";
                resultSet = statement.executeQuery(sql4);
                while(resultSet.next())
                {
                    amount = resultSet.getDouble("Price")*0.25;
                }
                HSubmit.setText("Submit");
                
                
            String sql3 = "INSERT INTO guest(name,type,number,email) VALUES(?,?,?,?)";
		
			
			PreparedStatement pst = connection.prepareStatement(sql3);
			pst.setString(1,G.getName());
			pst.setString(2,G.getType());
			pst.setString(3,G.getNumber());
			pst.setString(4,G.getEmail());
                        
			pst.executeUpdate();
                        
                        }
         catch (Exception e) {
                e.printStackTrace();
                }
        try{
                
                
            String sql = "INSERT INTO reservation(tableNo,NoOfGuests,time,date,guestId,type) VALUES(?,0,?,?,?,?)";


                             PreparedStatement pst2 = connection.prepareStatement(sql);
                             pst2.setInt(1,Number);
                             pst2.setInt(2,time);
                             pst2.setDate(3,date);
                             pst2.setInt(4,G.getID());
                             pst2.setString(5,HType1.getSelectedItem().toString());
                             

                             pst2.executeUpdate();
            
            
                    
        
            String sql5 = "INSERT INTO payment(amount,type,GuestID,discount) "
                                + "VALUES ("+amount+",'Hall Reservation Advance',"+G.getID()+",0)";
                        try
                            {
                                PreparedStatement pst = connection.prepareStatement(sql5);
                                pst.executeUpdate();
                            }
                            catch(SQLException e)
                            {
                                    System.out.println(e.getMessage());
                            }
            
            
            
        
         }
         catch (Exception e) {
                e.printStackTrace();
                }
       
        
            
            Form_Reservation1 R1 = new Form_Reservation1();
            R1.setVisible(true);
            R1.setLocationRelativeTo(this);
            R1.setExtendedState(JFrame.MAXIMIZED_BOTH);
            Form_Alerts A = new Form_Alerts("Hall has been reserved");
            A.setVisible(true);
            A.setDefaultCloseOperation(0);
            A.setVisible(true);
            A.setLocationRelativeTo(this);
            this.dispose();
        
    }//GEN-LAST:event_HSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Form_HallBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Form_HallBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Form_HallBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Form_HallBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Form_HallBookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker BDate;
    private javax.swing.JLabel HCheck;
    private javax.swing.JButton HSubmit;
    private javax.swing.JComboBox<String> HType;
    private javax.swing.JComboBox<String> HType1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
